version: "3.2"
services:
  php:
    build: "./docker/dev/php"
    networks:
      - backend
    volumes:
      - ./app/server/:/var/www/html/
  apache:
    build: "./docker/dev/apache"
    depends_on:
      - php
      - mysql
    networks:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./app/server/:/var/www/html/
  mysql:
    build: "./docker/dev/mysql"
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
  node:
    build: "./docker/dev/node"
    volumes:
      - ./app:/app
    working_dir: /app/client
    networks:
      - backend
    command: "npm run start"
    ports:
      - "8081:8081"
  phpmyadmin:
    build: "./docker/dev/phpmyadmin"
    depends_on:
      - mysql
    restart: always
    links:
      - mysql:mysql
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: rootpassword
      PMA_HOST: mysql
    networks:
      - backend

networks:
  backend:
