version: "3.2"
services:
  php:
    build: './docker/php'
    networks:
      - backend
    volumes:
      - ./app/server/:/var/www/html/
  apache:
    build: './docker/apache'
    depends_on:
      - php
      - mysql
    networks:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./app/server/:/var/www/html/
  mysql:
    image: mysql:5.6.40
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
  admin:
    image: fw/node:9.11.1-slim
    volumes:
      - ./app:/app
    working_dir: /app/client
    networks:
      - backend
    command: "npm run start"
    ports:
      - "8081:8081"

networks:
  backend: